### ISSUE TITLE
Begrüssung

### ISSUE THREAD

**Issue by drjakob** [kabel42/reporter.box#1]
Als Anwender
möchte ich beim Start von der reporter.box mit ihrer ID begrüsst werden, damit ich sie im story.board identifizieren kann.

Vorschlag: "My name is reporter.box Maria Leitner. Start Reporting". Für 5 Sekunden einblenden.

**Comment by kabel42** [comment]
Der Name wird immer Angezeigt, wenn die Anzeige für nichts anderes benutzt wird.
