### ISSUE TITLE
Namen der Box

### ISSUE THREAD

**Issue by drjakob** [kabel42/reporter.box#2]
Als Anwender möchte ich
dass jede Reporterbox einen unverwechselbaren Namen hat, damit ich sie über das Netz identifizieren kann.

Vorschlag: Namen hart coden.

**Comment by kabel42** [comment]
Vielleicht können wir den Particle Namen benutzen
https://docs.particle.io/reference/firmware/photon/#deviceid-

**Comment by drjakob** [comment]
Technisch naheliegend. Aber da wir nur eine handvoll Boxen haben, dachte ich an etwas pathetisches wie "Legendäre Reporterinnen".

**Comment by kabel42** [comment]
Die doku ist da nicht ganz eindeutig, das könnte der Name sein, den du dem Photon auf der Seite gibst

**Comment by drjakob** [comment]
Ok, gute Lösung

## 

Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 720 50 27

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage
