### ISSUE TITLE
Electron vs Photon

### ISSUE THREAD

**Issue by drjakob** [kabel42/reporter.box#5]
Als Hersteller(Admin) möchte ich
den Prozessor der Box zwischen Photon und Electron tauschen können, um auf verschiedene Einsatzzwecke mit Netzabdeckung reagieren zu können.

–> Die Firmware sollte eine entsprechende Erkennungsroutine bzw. einen Schalter haben.

**Comment by kabel42** [comment]
Was an der Firmware soll sich denn unterschiedlich verhalten?

**Comment by drjakob** [comment]
Sie soll es wissen und ans story.board/Display weitergeben, weil der Anwender es von außen nicht sieht.

**Comment by kabel42** [comment]
Im Idle wird angezeigt ob eine Sensorbox WiFi oder Cellular benutzt:
https://community.particle.io/t/solved-how-to-determine-electron-vs-photon-in-firmware/20177/5
